services:
  - type: web
    name: github-repo-tree-visualizer
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production 